headers:
    Authorization:
        type: string
        example: Bearer AccessToken
        required: true
        description: Client access token obtained by posting `/oauth/v2/token` with client_credentials grant_type