queryParameters:
    expand:
        description: Comma separated fields list to expand (can be nested)
        type: string
        required: false
        example: relation1,relation2.sub_relation

