queryParameters:
    page:
        description: Page number
        type: integer
        required: false
        default: 1
        example: 1
    per-page:
        description: Items on page count
        type: integer
        required: false
        default: 20
        example: 20