queryParameters:
    order-by:
        description: Sorting by fields (pattern 'field|direction', where 'field' is field to sort, and 'direction' is optional and can be 'asc' which is default value and 'desc')
        type: string
        required: false
        example: name|desc

